### ISSUE TITLE
IMPORT FAILED. Pls have a look at this error log

### ISSUE THREAD

**Issue by Zdeto** [cozymantis/human-parser-comfyui-node#8]
[comfyui.log](https://github.com/cozymantis/human-parser-comfyui-node/files/14933510/comfyui.log)
I started a developer command prompt for VS2019, fired up comfyui with run_nvidia_gpu.bat. It's a fresh and clean installation.
ninja is in the PATH. What is wrong? :)
Windows 11 Pro here.

**Comment by mosobln** [comment]
![image](https://github.com/cozymantis/human-parser-comfyui-node/assets/97992675/56024b74-ff3b-4dbc-bac7-f4cca9ea494e)

**Comment by gabidobo** [comment]
@mosobln you have a different issue according to your logs:

```
 Command '['which', 'c++']' returned non-zero exit status 1.
```

So basically you don't have c++ installed, but the node requires it to compile some python extensions.

See https://cloud.google.com/cpp/docs/setup or https://learn.microsoft.com/en-us/cpp/build/vscpp-step-0-installation?view=msvc-170
